name = "dkb"
description = "Simple Python Keybinder for linux (Xorg)"
version = "0.2.0"
url = "https://github.com/denischevalier/dkb/"
license = "GPLv3"
author = "Denis Chevalier"
author_email = "chevalierdenis@gmx.com"
platform = "Linux"
